### ISSUE TITLE
替换文件后打开报错了

### ISSUE THREAD

**Issue by xianggau** [asxez/DockerDesktop-CN#12]
替换文件后打开报错了
![微信图片_20240709141148](https://github.com/asxez/DockerDesktop-CN/assets/23502775/63c52a0b-550a-450c-8482-abc09a3827ac)

**Comment by asxez** [comment]
注意匹配版本

**Comment by asxez** [comment]
> 替换文件后打开报错了 ![微信图片_20240709141148](https://private-user-images.githubusercontent.com/23502775/346840372-63c52a0b-550a-450c-8482-abc09a3827ac.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MjQ4NjgsIm5iZiI6MTcyMDUyNDU2OCwicGF0aCI6Ii8yMzUwMjc3NS8zNDY4NDAzNzItNjNjNTJhMGItNTUwYS00NTBjLTg0ODItYWJjMDlhMzgyN2FjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDExMjkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjZjQwYTAyMTAyY2FlZGM2MDQyMzY3NWI5YzdhYjhlNDcxNzhmOWRkZTI0ZWYyNzFjNGQwZjNhMjBmMzE1OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j-3TPEZY_IhT3-JfZFFEg1sz8wiPMMQJxeExI9FRLQo)

注意匹配版本
