### ISSUE TITLE
步骤可以详细点吗

### ISSUE THREAD

**Issue by S1350** [asxez/DockerDesktop-CN#14]
v4.32.0版本  首先：C:\Program Files\Docker\Docker\resources  这个路径下面没有这个  app.asar的文件 ，其次，放进来后重启docker 也没有反应。

**Comment by S1350** [comment]
> 首先：C:\Program Files\Docker\Docker\resources 这个路径下面没有这个 app.asar的文件

其次，放进来后重启docker 也没有反应

**Comment by sakdd** [comment]
你没有阅读文档吗？？？

**Comment by asxez** [comment]
> v4.32.0版本 首先：C:\Program Files\Docker\Docker\resources 这个路径下面没有这个 app.asar的文件 ，其次，放进来后重启docker 也没有反应。

找你的安装路径，你这个路径默认的话也是错的，仔细看文档。
