### ISSUE TITLE
win10汉化包有问题

### ISSUE THREAD

**Issue by zilong1211806606** [asxez/DockerDesktop-CN#16]
win10系统用汉化包会导致桌面点击图标无法启动的问题，（昨天在公司的笔记本电脑也安装了汉化包，但是可以，都是官网下载的最新程序，不存在版本问题）

**Comment by asxez** [comment]
> win10系统用汉化包会导致桌面点击图标无法启动的问题，（昨天在公司的笔记本电脑也安装了汉化包，但是可以，都是官网下载的最新程序，不存在版本问题）

看看任务管理器docker是否在运行。
公司电脑也是win10吗？如果是的话应该跟系统和汉化包没关系。

**Comment by zilong1211806606** [comment]
公司电脑是win11的，汉化后可以正常使用。至于家里的电脑是win10的，点击桌面图标无反应，任务管理器里面是有线程的，结束线程后再次点击应用还是无反应。最后只能放弃汉化，把替换的文件还原后就可以正常启动程序了。
&nbsp;


紫泷
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年8月17日(星期六) 下午2:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [asxez/DockerDesktop-CN] win10汉化包有问题 (Issue #16)














  
win10系统用汉化包会导致桌面点击图标无法启动的问题，（昨天在公司的笔记本电脑也安装了汉化包，但是可以，都是官网下载的最新程序，不存在版本问题）
  
看看任务管理器docker是否在运行。
 公司电脑也是win10吗？如果是的话应该跟系统和汉化包没关系。

**Comment by asxez** [comment]
> 公司电脑是win11的，汉化后可以正常使用。至于家里的电脑是win10的，点击桌面图标无反应，任务管理器里面是有线程的，结束线程后再次点击应用还是无反应。最后只能放弃汉化，把替换的文件还原后就可以正常启动程序了。 &nbsp; 紫泷 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年8月17日(星期六) 下午2:46 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [asxez/DockerDesktop-CN] win10汉化包有问题 (Issue #16) win10系统用汉化包会导致桌面点击图标无法启动的问题，（昨天在公司的笔记本电脑也安装了汉化包，但是可以，都是官网下载的最新程序，不存在版本问题） 看看任务管理器docker是否在运行。 公司电脑也是win10吗？如果是的话应该跟系统和汉化包没关系。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

那应该就是系统的原因，这边暂时解决不了。
