### ISSUE TITLE
win11替换文件后，docker无法打开

### ISSUE THREAD

**Issue by caoyuee** [asxez/DockerDesktop-CN#17]
按照readme的步骤，下载window11 的汉化包，我的版本是32的，所以下载的是win 32的包，替换掉文件后docker desktop就打不开了，把之前的文件再换回去，就可以打开了

**Comment by asxez** [comment]
> 按照readme的步骤，下载window11 的汉化包，我的版本是32的，所以下载的是win 32的包，替换掉文件后docker desktop就打不开了，把之前的文件再换回去，就可以打开了

汉化包是通过测试后才会发布的，建议你更新docker至最新版本，或者前往脚本仓库使用脚本进行汉化。
