### ISSUE TITLE
请问在mac上如何操作？

### ISSUE THREAD

**Issue by Kong4Git** [asxez/DockerDesktop-CN#20]
我把文件放到了mac中相应的位置，重新打开的时候就会报错，导致无法启动，实在是痛苦

**Comment by Kong4Git** [comment]
![截屏2024-08-28 00 32 45](https://github.com/user-attachments/assets/1fa6c5b0-f331-4d14-bc3e-1321915c223f)

**Comment by Kong4Git** [comment]
已经自己解决是文件processor.py中文件相关文件路径的问题，调整完后可以正常汉化了，然后asar文件不用替换，使用app原本的app.asar文件就好

<img width="1491" alt="image" src="https://github.com/user-attachments/assets/baad0c89-cbbe-4202-8334-8c106a94b8be">

**Comment by xunWuKong** [comment]
你好，我也遇到了同样的问题，你应该也是Apple芯片的Mac吧。
你后续是怎么调整的？没用作者的app.asar包，自己跑DDCS工程汉化的嘛？调整了processor.py文件哪些代码？

**Comment by Kong4Git** [comment]
> 你好，我也遇到了同样的问题，你应该也是Apple芯片的Mac吧。 你后续是怎么调整的？没用作者的app.asar包，自己跑DDCS工程汉化的嘛？调整了processor.py文件哪些代码？


是的m3max，我现在正常使用， 就是我调整了processor.py里面的app本地路径。我估计作者应该已经修复了问题。
