### ISSUE TITLE
MacOS 执行汉化脚本报错

### ISSUE THREAD

**Issue by njleiyin** [asxez/DockerDesktop-CN#21]
##系统

macos 13.6.6

##docker版本
 [4.33.0](https://docs.docker.com/desktop/release-notes/#4330)

##执行脚本时报错，报错信息
文件复制时出错: [Errno 1] Operation not permitted: '/Applications/Docker.app/Contents/MacOS/Docker Desktop.app/Contents/Resources/app.asar'

<img width="839" alt="image" src="https://github.com/user-attachments/assets/bd81992e-2925-4102-9eb1-4d9b2e40a7cc">

**Comment by asxez** [comment]
> ##系统
> 
> macos 13.6.6
> 
> ##docker版本 [4.33.0](https://docs.docker.com/desktop/release-notes/#4330)
> 
> ##执行脚本时报错，报错信息 文件复制时出错: [Errno 1] Operation not permitted: '/Applications/Docker.app/Contents/MacOS/Docker Desktop.app/Contents/Resources/app.asar'
> 
> <img alt="image" width="839" src="https://private-user-images.githubusercontent.com/25842181/362234062-bd81992e-2925-4102-9eb1-4d9b2e40a7cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MDg4NTQsIm5iZiI6MTcyNDkwODU1NCwicGF0aCI6Ii8yNTg0MjE4MS8zNjIyMzQwNjItYmQ4MTk5MmUtMjkyNS00MTAyLTllYjEtNGQ5YjJlNDBhN2NjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDA1MTU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2NjY0MjM0ZTJlMzE5OWY4MTY5ODcyYWViZDg3MWEzODMxM2RkM2ZmMTQxOWZlOGYyZDlmNmZiZDM4OGExOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OFhflFPQHcj6B_PBRSZqQZMgIpuRpvWbvAc9KI9HAPk">

这个是你磁盘没有权限的原因，不是脚本的问题。
