### ISSUE TITLE
想要Mac ARM架构的包

### ISSUE THREAD

**Issue by xunWuKong** [asxez/DockerDesktop-CN#22]

**Comment by asxez** [comment]
> _No description provided._

MAC有ARM架构的吗？不是只有苹果芯和英特尔芯的吗？

**Comment by xunWuKong** [comment]
苹果芯就是ARM架构。M系列都是ARM架构
所以分为：ARM 64-bit 和 x86 64-bit

**Comment by asxez** [comment]
> 苹果芯就是ARM架构。M系列都是ARM架构 所以分为：ARM 64-bit 和 x86 64-bit

已更新

**Comment by xunWuKong** [comment]
大佬，我是指 app.asar 这个文件，现在仓库中的这个app-4.3-mac.asar 是英特尔芯 x64的，Apple芯片的用不了

**Comment by asxez** [comment]
> 大佬，我是指 app.asar 这个文件，现在仓库中的这个app-4.3-mac.asar 是英特尔芯 x64的，Apple芯片的用不了

汉化包的话建议下载汉化脚本进行汉化，我用不了苹果芯的macos

**Comment by xunWuKong** [comment]
[app-4.34-mac-apple.asar.zip](https://github.com/user-attachments/files/16862645/app-4.34-mac-apple.asar.zip)

我自己本地跑了个，可用。

**Comment by boynton89** [comment]
![QQ_1729014964669](https://github.com/user-attachments/assets/70845317-1fda-46ef-a8fe-fd570501b6e9)
用脚本跑完后提示这个怎么办a ?
