### ISSUE TITLE
无法解包npx

### ISSUE THREAD

**Issue by frui85** [asxez/DockerDesktop-CN#24]
![image](https://github.com/user-attachments/assets/c56b917d-16cf-4b96-97c1-d191593d4e79)

**Comment by asxez** [comment]
> ![image](https://private-user-images.githubusercontent.com/10277372/363599569-c56b917d-16cf-4b96-97c1-d191593d4e79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNjU0NzcsIm5iZiI6MTcyNTI2NTE3NywicGF0aCI6Ii8xMDI3NzM3Mi8zNjM1OTk1NjktYzU2YjkxN2QtMTZjZi00Yjk2LTk3YzEtZDE5MTU5M2Q0ZTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDA4MTkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhZjcxY2U4MmMyMGIyNjZhODM1NGYyODFkODk1ODdhNzViNWRkOWE0NTBhNzg2YmFmOThhMDAyYTQ1MDY5OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rgEIVUqD3CR4kJ3KmpO1zZm8d-gn9cuwkus4rIzSgXU)

需要下载nodejs
