### ISSUE TITLE
（macos arm）macos的咋替换啊 我没找到对应的app.asar

### ISSUE THREAD

**Issue by Elijah-Guo** [asxez/DockerDesktop-CN#25]
<img width="536" alt="image" src="https://github.com/user-attachments/assets/22af9344-33f9-4b54-a78c-fd180713eb3b">

**Comment by asxez** [comment]
> <img alt="image" width="536" src="https://private-user-images.githubusercontent.com/38368558/364239747-22af9344-33f9-4b54-a78c-fd180713eb3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MzA0MzEsIm5iZiI6MTcyNTQzMDEzMSwicGF0aCI6Ii8zODM2ODU1OC8zNjQyMzk3NDctMjJhZjkzNDQtMzNmOS00YjU0LWE3OGMtZmQxODA3MTNlYjNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDA2MDg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2MjQ4NDM0NTY1OWE3OGI4MzlmYzViYTk0MWY4ZDMwMTZjYzMwMmMwMDgzOWYzYjNmMmM4OTUxNmUyZWYxNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.75n9KJ64zP1Ni5s6MtgowFiEeiFKmHIhcTYudMhweFk">

/Applications/Docker.app/Contents/MacOS/Docker Desktop.app/Contents/Resources

**Comment by Elijah-Guo** [comment]
<img width="1501" alt="image" src="https://github.com/user-attachments/assets/4252ee16-787a-4996-a7c5-fb1a851312ce">
我去 不支持arm么

**Comment by Elijah-Guo** [comment]
<img width="319" alt="image" src="https://github.com/user-attachments/assets/3b991981-e5a1-44f3-875c-57457f944ca1">

**Comment by asxez** [comment]
> <img alt="image" width="1501" src="https://private-user-images.githubusercontent.com/38368558/364252689-4252ee16-787a-4996-a7c5-fb1a851312ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MzU2MDQsIm5iZiI6MTcyNTQzNTMwNCwicGF0aCI6Ii8zODM2ODU1OC8zNjQyNTI2ODktNDI1MmVlMTYtNzg3YS00OTk2LWE3YzUtZmIxYTg1MTMxMmNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDA3MzUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0MjgzOTRiOGVjZDYzZWIwNWFiM2E2YzNlMzIyNjQ1NjU3M2ViNzcwODdmMDQ4OGUxMDkwYmUzYmVjMzBlNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yMn4W6lwLgQ46AsLBsbLTRno15vR2QjNNkNcAF_QHvI"> 我去 不支持arm么

建议下载汉化脚本进行汉化，我没有arm架构的macos
