### ISSUE TITLE
请问大佬，mac上怎么汉化？

### ISSUE THREAD

**Issue by jlhulclq** [asxez/DockerDesktop-CN#28]

**Comment by asxez** [comment]
> _No description provided._

路径默认为`/Applications/Docker.app/Contents/MacOS/Docker Desktop.app/Contents/Resources`

**Comment by jlhulclq** [comment]
谢谢，可是我把文件放进去，并没有用。

**Comment by asxez** [comment]
> 谢谢，可是我把文件放进去，并没有用。

仔细读文档，版本号匹配，实在不行就去下载脚本进行汉化

**Comment by jlhulclq** [comment]
好的，谢谢。
