### ISSUE TITLE
mac apple silicon上汉化有问题

### ISSUE THREAD

**Issue by huyang7902** [asxez/DockerDesktop-CN#31]
版本：4.34
m1替换之后，启动报如下错误
![image](https://github.com/user-attachments/assets/c9f8d1f8-17fe-47c2-acee-9606ae43edfc)

**Comment by asxez** [comment]
> 版本：4.34 m1替换之后，启动报如下错误 ![image](https://private-user-images.githubusercontent.com/26130705/371025841-c9f8d1f8-17fe-47c2-acee-9606ae43edfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzU1OTIsIm5iZiI6MTcyNzMzNTI5MiwicGF0aCI6Ii8yNjEzMDcwNS8zNzEwMjU4NDEtYzlmOGQxZjgtMTdmZS00N2MyLWFjZWUtOTYwNmFlNDNlZGZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA3MjEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlZGNkOGI2NDk3MDM5NWZiMmZmYjhiNTU5ZDc0YjJlMjM5ZTIyMTdiMzUxNDA4NDMyMGU0MzAyZTcwNjViOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4UU_xzTCJTY8a9ycGa4rkm2mmxZ5gy45NVyoBL0sdPE)

本仓库macos汉化包不支持苹果芯，可以下载汉化脚本进行汉化
