### ISSUE TITLE
Mac M2系列的芯片无法正常使用

### ISSUE THREAD

**Issue by AdamZay** [asxez/DockerDesktop-CN#32]

**Comment by AdamZay** [comment]
用asar文件替换后，Mac  ARM系列芯片的电脑会报以下错误
![WechatIMG5](https://github.com/user-attachments/assets/b8d28fea-76cf-41cd-a147-f33bea907889)

**Comment by asxez** [comment]
> 用asar文件替换后，Mac ARM系列芯片的电脑会报以下错误 ![WechatIMG5](https://private-user-images.githubusercontent.com/113489584/372315152-b8d28fea-76cf-41cd-a147-f33bea907889.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3NTU1MzksIm5iZiI6MTcyNzc1NTIzOSwicGF0aCI6Ii8xMTM0ODk1ODQvMzcyMzE1MTUyLWI4ZDI4ZmVhLTc2Y2YtNDFjZC1hMTQ3LWYzM2JlYTkwNzg4OS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQwNDAwMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNmFjZmRhMGE3YTg3MGQwZDg5OTliMDczNmQ3NGJlMWRmOGMxNDMyZmJhNzRiNjhmODM0ZGUwMzBmYjA1MDBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._irQyP21Xb1gnhlEeyhYTLV7gkR3K4K90SvtvW2feGc)

解决方案已经在 #22 里了

**Comment by AdamZay** [comment]
谢谢大佬，解决了。
