### ISSUE TITLE
mac 4.34不好用

### ISSUE THREAD

**Issue by loiasdi** [asxez/DockerDesktop-CN#33]
mac 4.34不好用，更换完直接报错

**Comment by RedWolfChaoo** [comment]
我尝试了4.3.4,4.3.3, 4.3.2都不可用. 且使用 https://github.com/asxez/DDCS 这个脚本也不可用.
最终全网搜了下, 没有解决. 放弃汉化

**Comment by asxez** [comment]
本仓库的mac版本只支持intel芯，脚本是可以用的，具体见仓库ReadMe。
