### ISSUE TITLE
无法汉化，路径查找不到

### ISSUE THREAD

**Issue by SayNo233** [asxez/DockerDesktop-CN#5]
hi，作者你好。版本是这个，下载的是for MAC 版本。机器是M2系统。路径没有找到同名文件，只有新增，没有替换。
<img width="1252" alt="image" src="https://github.com/asxez/DockerDesktop-CN/assets/59193922/e19d7f1e-bcba-4001-ac34-5a61023fbe3c">

<img width="756" alt="image" src="https://github.com/asxez/DockerDesktop-CN/assets/59193922/48a8efac-462d-4758-ad95-6726dd0194da">
请问是为什么？需要怎么弄才能汉化成功？

**Comment by asxez** [comment]
这个是Windows版本的，MAC用不了。

**Comment by asxez** [comment]
> hi，作者你好。版本是这个，下载的是for MAC 版本。机器是M2系统。路径没有找到同名文件，只有新增，没有替换。 <img alt="image" width="1252" src="https://private-user-images.githubusercontent.com/59193922/339241624-e19d7f1e-bcba-4001-ac34-5a61023fbe3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNjQzNDIsIm5iZiI6MTcxODI2NDA0MiwicGF0aCI6Ii81OTE5MzkyMi8zMzkyNDE2MjQtZTE5ZDdmMWUtYmNiYS00MDAxLWFjMzQtNWE2MTAyM2ZiZTNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDA3MzQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwMDZmZGM4NmFmYjdjODZkMDYzMmJkZTcwMjMyYmY4NzdhMjc5ZTZhZmJhODYxZWQwNDY3MjQxMDliYzE2ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fGliKIBQV_WE8zdRLRjbBYwrAw0up89P-Btpl-Upa_k">
> 
> <img alt="image" width="756" src="https://private-user-images.githubusercontent.com/59193922/339242025-48a8efac-462d-4758-ad95-6726dd0194da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNjQzNDIsIm5iZiI6MTcxODI2NDA0MiwicGF0aCI6Ii81OTE5MzkyMi8zMzkyNDIwMjUtNDhhOGVmYWMtNDYyZC00NzU4LWFkOTUtNjcyNmRkMDE5NGRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDA3MzQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyZmJhN2JhNjZlNjgzYzRlMWZkN2QxZDgwZTg2NmFhMGNmMzhmODk4YjdiOWI1NzM1NzE5YWM1ZjQ0YmIyZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xL3HGX9WEXqG6pyFbn8Y5cCO_kgtdp5R6AlbN_t_EDg"> 请问是为什么？需要怎么弄才能汉化成功？

这个是Windows版本的，MAC用不了。
