### ISSUE TITLE
汉化个mac版的呗。。。。。。。。。

### ISSUE THREAD

**Issue by 464917671** [asxez/DockerDesktop-CN#6]
汉化个mac版的呗。。。。。。。。。

**Comment by 464917671** [comment]
[Uploading app.asar.bak.zip…]()
docker desktop 4.3.0  for mac

**Comment by 464917671** [comment]
你能不能写个脚本来汉化啊。复制粘贴麻烦不说，还每次更细都要来一遍。我有一个想法，可以试试脚本一键实现，类似：import zipfile
import os
import shutil

# Define the file paths
zip_file_path = '/mnt/data/interface_translation.zip'
extract_dir = '/mnt/data/extracted'
translated_dir = '/mnt/data/translated'

# Create directories if they don't exist
os.makedirs(extract_dir, exist_ok=True)
os.makedirs(translated_dir, exist_ok=True)

# Extract the zip file
with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extract_dir)

# Dictionary for translation (example)
translations = {
    "File": "文件",
    "Edit": "编辑",
    "View": "视图",
    "Help": "帮助",
    # Add more translations as needed
}

# Function to translate text
def translate_text(text, translations):
    for eng, chn in translations.items():
        text = text.replace(eng, chn)
    return text

# Function to read file with different encodings
def read_file_with_encodings(file_path):
    encodings = ['utf-8', 'latin1', 'iso-8859-1']
    for encoding in encodings:
        try:
            with open(file_path, 'r', encoding=encoding) as f:
                return f.read()
        except UnicodeDecodeError:
            continue
    raise UnicodeDecodeError(f"Unable to decode the file: {file_path}")

# Walk through the extracted files and translate
for root, dirs, files in os.walk(extract_dir):
    for file in files:
        file_path = os.path.join(root, file)
        try:
            content = read_file_with_encodings(file_path)
            translated_content = translate_text(content, translations)
            translated_file_path = os.path.join(translated_dir, os.path.relpath(file_path, extract_dir))
            os.makedirs(os.path.dirname(translated_file_path), exist_ok=True)
            with open(translated_file_path, 'w', encoding='utf-8') as f:
                f.write(translated_content)
        except UnicodeDecodeError as e:
            print(f"Error reading file {file_path}: {e}")

# Create a new zip file with the translated content
translated_zip_path = '/mnt/data/translated_interface.zip'
shutil.make_archive(translated_zip_path.replace('.zip', ''), 'zip', translated_dir)
translated_zip_path

**Comment by asxez** [comment]
> 汉化个mac版的呗。。。。。。。。。



> 汉化个mac版的呗。。。。。。。。。

请转#4

**Comment by asxez** [comment]
> #能不能写个脚本来汉化啊。复制粘贴麻烦不说，还每次更细都要来一遍。我有一个想法，可以试试脚本一键实现，类似： Uploading example.txt…



> #能不能写个脚本来汉化啊。复制粘贴麻烦不说，还每次更细都要来一遍。我有一个想法，可以试试脚本一键实现，类似： Uploading example.txt…



> #能不能写个脚本来汉化啊。复制粘贴麻烦不说，还每次更细都要来一遍。我有一个想法，可以试试脚本一键实现，类似： Uploading example.txt…

脚本后期可能会出，敬请期待。

**Comment by 464917671** [comment]
非常感谢，我写完了。
![1719290717550](https://github.com/asxez/DockerDesktop-CN/assets/53884768/affed9e5-3265-4bcb-9428-af566bd32375)

**Comment by 464917671** [comment]
我开源吧，希望有人完善。

**Comment by 464917671** [comment]
开源给你了。懒得动了。
[Uploading docker汉化formac.zip…]()

**Comment by TIANXUAN13** [comment]
> 非常感谢，我写完了。 ![1719290717550](https://private-user-images.githubusercontent.com/53884768/342585767-affed9e5-3265-4bcb-9428-af566bd32375.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMTY5NjMsIm5iZiI6MTcyMzAxNjY2MywicGF0aCI6Ii81Mzg4NDc2OC8zNDI1ODU3NjctYWZmZWQ5ZTUtMzI2NS00YmNiLTk0MjgtYWY1NjZiZDMyMzc1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDA3NDQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2Y2Y0M2Y5NTlmYjVkYzQ5ODM2MDJiNTAzZDE0YTBhYjhiOTZmMDM0NmEzYWU0ZmE5MzFlNDVlMWE5ZTEwMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ogYDefUmuAvMwFcOBgTiedPwVO0uSB7w9PfQHY5DZ_4)

老哥这个 mac 版本的汉化包可以给一下吗，非常感谢

**Comment by 464917671** [comment]
> > 非常感谢，我写完了。 ![1719290717550](https://private-user-images.githubusercontent.com/53884768/342585767-affed9e5-3265-4bcb-9428-af566bd32375.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMTY5NjMsIm5iZiI6MTcyMzAxNjY2MywicGF0aCI6Ii81Mzg4NDc2OC8zNDI1ODU3NjctYWZmZWQ5ZTUtMzI2NS00YmNiLTk0MjgtYWY1NjZiZDMyMzc1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDA3NDQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2Y2Y0M2Y5NTlmYjVkYzQ5ODM2MDJiNTAzZDE0YTBhYjhiOTZmMDM0NmEzYWU0ZmE5MzFlNDVlMWE5ZTEwMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ogYDefUmuAvMwFcOBgTiedPwVO0uSB7w9PfQHY5DZ_4)
> 
> 老哥这个 mac 版本的汉化包可以给一下吗，非常感谢

劝你学python，https://blog.csdn.net/qq464917671/article/details/140398831

**Comment by TIANXUAN13** [comment]
> > > 非常感谢，我写完了。 ![1719290717550](https://private-user-images.githubusercontent.com/53884768/342585767-affed9e5-3265-4bcb-9428-af566bd32375.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMTY5NjMsIm5iZiI6MTcyMzAxNjY2MywicGF0aCI6Ii81Mzg4NDc2OC8zNDI1ODU3NjctYWZmZWQ5ZTUtMzI2NS00YmNiLTk0MjgtYWY1NjZiZDMyMzc1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDA3NDQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2Y2Y0M2Y5NTlmYjVkYzQ5ODM2MDJiNTAzZDE0YTBhYjhiOTZmMDM0NmEzYWU0ZmE5MzFlNDVlMWE5ZTEwMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ogYDefUmuAvMwFcOBgTiedPwVO0uSB7w9PfQHY5DZ_4)
> > 
> > 
> > 老哥这个 mac 版本的汉化包可以给一下吗，非常感谢
> 
> 劝你学python，https://blog.csdn.net/qq464917671/article/details/140398831

老哥牛逼，我学过一点 python 看得懂一点，写的垃圾，非常感谢您，祝您秋天快乐吖
